# Site settings
title: Wayfare Labs
description: Change this description.
url: http://wayfarelabs.org
company:
  name: Wayfare Labs
  email: hi@wayfarelabs.org
  street: 270 Baker St E Ste 200
  city: Costa Mesa
  state: CA
  postal_code: 92626
  phone: (714) 598-3888

# Build settings
encoding: utf-8
timezone: US/Pacific
exclude:
  - .divshot-cache
  - .gitignore
  - .ruby-version
  - _config.yml
  - CNAME
  - divshot.json
  - Gemfile
  - Gemfile.lock
  - README.md
markdown: kramdown
kramdown:
  entity_output: :symbolic
relative_permalinks: true
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
  js_compressor: uglifier
  css_compressor: sass
  cachebust: hard

# Post permalink style
permalink: /blog/:year/:month/:title/

# Page defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      logo:
        link: /
      header:
        template: "header.html"
      nav:
        template: "nav.html"
      body:
        wide: false
      footer:
        sticky: true
        template: "footer.html"
