# Site settings
title: Wayfare Labs
email: hi@wayfarelabs.org
description: "We believe in the world's best future."
url: http://wayfarelabs.org
twitter_username: wayfarelabs

# Build settings
encoding: utf-8
timezone: US/Pacific
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "README.md", "divshot.json", ".divshot-cache"]
markdown: kramdown
kramdown:
  entity_output: :symbolic
relative_permalinks: true
assets:
  dirname: public-assets
  baseurl: /public-assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
  js_compressor: uglifier
  css_compressor: sass
  cachebust: hard

# Post permalink style
permalink: /blog/:year/:month/:title/

# Page defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      logo:
        link: /
      header:
        template: "header.html"
      body:
        wide: false
      footer:
        sticky: true
        template: "footer.html"
